---
title: "0.2_data cleaning based on info"
author: "Ju-Chi.Yu"
date: "10/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

load("../Data/AllPunctCount.sDisCA.rda")

### Change this line ========================================================
raw.dx <- readxl::read_xlsx("../Data/Author.design.xlsx") %>% as.data.frame
#============================================================================


## combine - and n-dash
alldat.cmb <- cbind(AllPunctCount.sDisCA[, c(1,2,3,4,5,6,9,10)], AllPunctCount.sDisCA[,7] + AllPunctCount.sDisCA[,8])
frdat.cmb <- cbind(AllPunctCount.sDisCA.fr[, c(1,2,3,4,5,6,9,10)], AllPunctCount.sDisCA.fr[,7] + AllPunctCount.sDisCA.fr[,8])
endat.cmb <- cbind(AllPunctCount.sDisCA.en[, c(1,2,3,4,5,6,9,10)], AllPunctCount.sDisCA.en[,7] + AllPunctCount.sDisCA.en[,8])
colnames(endat.cmb)[9] <- colnames(frdat.cmb)[9] <- colnames(alldat.cmb)[9] <- "-\u2013"

## delete duplicated and all-zeros rows
alldat.cmb <- alldat.cmb[duplicated(alldat.cmb) == FALSE,]
frdat.cmb  <- frdat.cmb[duplicated(frdat.cmb) == FALSE,]
endat.cmb  <- endat.cmb[duplicated(endat.cmb) == FALSE,]

# specify different row names for Poe, Edgar Allan
rownames(frdat.cmb)[rownames(frdat.cmb) == "Poe, Edgar Allan"] <- "Poe, Edgar Allan (in French)"

```

## Data cleaning

+ Selection criteria: We excluded authors that punctuate less than 2000 times

```{r}
# check and remove duplicated rows (repeated authors)
raw.dx <- raw.dx[duplicated(raw.dx) == FALSE, ]
# recode "keep" and "Supp" columns
raw.dx$keep <- is.na(raw.dx$keep)
raw.dx$Supp <- !is.na(raw.dx$Supp)

# recode Time
Time.idx <- c(`18th` = "18th and before", `17th` = "18th and before", `14th` = "18th and before", `16th` = "18th and before", `20th` = "20th on", `21st` = "20th on")
raw.dx$Time.recod <- recode(raw.dx$Time, !!! Time.idx)

# make these four columns factors
raw.dx[,c("Language", "Nationality", "Type", "Time", "Time.recod")] <- lapply(raw.dx[,c("Language", "Nationality", "Type", "Time", "Time.recod")], factor)

data.dx <- raw.dx[which(raw.dx$keep == "TRUE" & raw.dx$Supp == "FALSE"),]
supp.dx <- raw.dx[which(raw.dx$keep == "TRUE" & raw.dx$Supp == "TRUE"),]

# specify different row names for Poe, Edgar Allan
data.dx[which(data.dx$Authors == "Poe, Edgar Allan" & data.dx$Language == "fr"),"Authors"] <- "Poe, Edgar Allan (in French)"

```

## Get data from the correct language

```{r}
## Create empty matrix
FrEnAuthors <- matrix(nrow  = nrow(data.dx), ncol = ncol(alldat.cmb), dimnames = list(data.dx$Authors, colnames(alldat.cmb)))

## extract authors' data from the English subset
en.author <- data.dx[which(data.dx$Language == "en"), "Authors"]
FrEnAuthors[en.author,] <- endat.cmb[en.author,]

## extract authors' data from the French subset
fr.author <- data.dx[which(data.dx$Language == "fr"), "Authors"]
FrEnAuthors[fr.author,] <- frdat.cmb[fr.author,]
```

## Get supplementary

```{r}
FrEnAuthors.supp <- matrix(nrow  = nrow(supp.dx), ncol = ncol(alldat.cmb), dimnames = list(supp.dx$Authors, colnames(alldat.cmb)))

## extract authors' data from the English subset
en.author.supp <- supp.dx[which(supp.dx$Language == "en"), "Authors"]
FrEnAuthors.supp[en.author.supp,] <- endat.cmb[en.author.supp,]

## extract authors' data from the French subset
fr.author.supp <- supp.dx[which(supp.dx$Language == "fr"), "Authors"]
FrEnAuthors.supp[fr.author.supp,] <- frdat.cmb[fr.author.supp,]
```

## Save cleaned authors data

```{r}
save(FrEnAuthors, data.dx, FrEnAuthors.supp, supp.dx, file = "../Data/EnFrAuthorsCleaned.rda")
```




